FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./turbo.json ./turbo.json
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock

COPY ./packages ./packages
COPY ./apps/http-backend ./apps/http-backend

RUN bun install
RUN bun turbo db:generate

EXPOSE 8080

CMD [ "bun", "run", "start:backend" ]