FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./turbo.json ./turbo.json
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock

COPY ./packages ./packages
COPY ./apps/ws-backend ./apps/ws-backend

RUN bun install
RUN bun turbo db:generate

EXPOSE 8081

CMD [ "bun", "run", "start:websocket" ]