name: deploy turborepo to vm

on:
  push:
    branches:
      - main

jobs:
  deploy_wedsocket:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push to dockerhub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.websocket
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-websocket:${{ github.sha }}

      - name: ssh into vm and the run docker image
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >& ~/ssh_key
          chmod 700 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.VM_HOST }} << 'EOF'
            echo "hello world"
            
            if ! docker network inspect todo-network >/dev/null 2>&1; then
              docker network create todo-network
            fi

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/todo-websocket:${{ github.sha }}

            if [ "$(docker ps -a -q -f name=todo-websocket)" ]; then
              docker rm -f todo-websocket
            fi

            docker run -d --name todo-websocket --network todo-app-network \
            -e DATABASE_URL="${{ secrets.DB_URL }}" -p 8081:8081 \
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-websocket:${{ github.sha }}

          EOF
